/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLotesRouteImport } from './routes/admin.lotes'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminLotesBatchIdRouteImport } from './routes/admin.lotes.$batchId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotesRoute = AdminLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotesBatchIdRoute = AdminLotesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => AdminLotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/lotes': typeof AdminLotesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/lotes': typeof AdminLotesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/lotes': typeof AdminLotesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/import'
    | '/admin/lotes'
    | '/admin/'
    | '/admin/lotes/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/import'
    | '/admin/lotes'
    | '/admin'
    | '/admin/lotes/$batchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/import'
    | '/admin/lotes'
    | '/admin/'
    | '/admin/lotes/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lotes': {
      id: '/admin/lotes'
      path: '/lotes'
      fullPath: '/admin/lotes'
      preLoaderRoute: typeof AdminLotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lotes/$batchId': {
      id: '/admin/lotes/$batchId'
      path: '/$batchId'
      fullPath: '/admin/lotes/$batchId'
      preLoaderRoute: typeof AdminLotesBatchIdRouteImport
      parentRoute: typeof AdminLotesRoute
    }
  }
}

interface AdminLotesRouteChildren {
  AdminLotesBatchIdRoute: typeof AdminLotesBatchIdRoute
}

const AdminLotesRouteChildren: AdminLotesRouteChildren = {
  AdminLotesBatchIdRoute: AdminLotesBatchIdRoute,
}

const AdminLotesRouteWithChildren = AdminLotesRoute._addFileChildren(
  AdminLotesRouteChildren,
)

interface AdminRouteChildren {
  AdminImportRoute: typeof AdminImportRoute
  AdminLotesRoute: typeof AdminLotesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportRoute: AdminImportRoute,
  AdminLotesRoute: AdminLotesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
