/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RotaIndexRouteImport } from './routes/rota.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RotaRouteCodeRouteImport } from './routes/rota.$routeCode'
import { Route as AdminVeiculosRouteImport } from './routes/admin.veiculos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminAnaliseRouteImport } from './routes/admin.analise'
import { Route as RotaRouteCodeIndexRouteImport } from './routes/rota.$routeCode.index'
import { Route as AdminMotoristasIndexRouteImport } from './routes/admin.motoristas.index'
import { Route as AdminLotesIndexRouteImport } from './routes/admin.lotes.index'
import { Route as RotaRouteCodeResumoRouteImport } from './routes/rota.$routeCode.resumo'
import { Route as RotaRouteCodeConfirmadaRouteImport } from './routes/rota.$routeCode.confirmada'
import { Route as AdminMotoristasDriverIdRouteImport } from './routes/admin.motoristas.$driverId'
import { Route as AdminLotesBatchIdRouteImport } from './routes/admin.lotes.$batchId'
import { Route as RotaRouteCodePracasIndexRouteImport } from './routes/rota.$routeCode.pracas.index'
import { Route as RotaRouteCodePracasSquareIdRouteImport } from './routes/rota.$routeCode.pracas.$squareId'
import { Route as AdminLotesBatchIdAlteracoesRouteImport } from './routes/admin.lotes.$batchId.alteracoes'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaIndexRoute = RotaIndexRouteImport.update({
  id: '/rota/',
  path: '/rota/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RotaRouteCodeRoute = RotaRouteCodeRouteImport.update({
  id: '/rota/$routeCode',
  path: '/rota/$routeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnaliseRoute = AdminAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AdminRoute,
} as any)
const RotaRouteCodeIndexRoute = RotaRouteCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RotaRouteCodeRoute,
} as any)
const AdminMotoristasIndexRoute = AdminMotoristasIndexRouteImport.update({
  id: '/motoristas/',
  path: '/motoristas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotesIndexRoute = AdminLotesIndexRouteImport.update({
  id: '/lotes/',
  path: '/lotes/',
  getParentRoute: () => AdminRoute,
} as any)
const RotaRouteCodeResumoRoute = RotaRouteCodeResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => RotaRouteCodeRoute,
} as any)
const RotaRouteCodeConfirmadaRoute = RotaRouteCodeConfirmadaRouteImport.update({
  id: '/confirmada',
  path: '/confirmada',
  getParentRoute: () => RotaRouteCodeRoute,
} as any)
const AdminMotoristasDriverIdRoute = AdminMotoristasDriverIdRouteImport.update({
  id: '/motoristas/$driverId',
  path: '/motoristas/$driverId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotesBatchIdRoute = AdminLotesBatchIdRouteImport.update({
  id: '/lotes/$batchId',
  path: '/lotes/$batchId',
  getParentRoute: () => AdminRoute,
} as any)
const RotaRouteCodePracasIndexRoute =
  RotaRouteCodePracasIndexRouteImport.update({
    id: '/pracas/',
    path: '/pracas/',
    getParentRoute: () => RotaRouteCodeRoute,
  } as any)
const RotaRouteCodePracasSquareIdRoute =
  RotaRouteCodePracasSquareIdRouteImport.update({
    id: '/pracas/$squareId',
    path: '/pracas/$squareId',
    getParentRoute: () => RotaRouteCodeRoute,
  } as any)
const AdminLotesBatchIdAlteracoesRoute =
  AdminLotesBatchIdAlteracoesRouteImport.update({
    id: '/alteracoes',
    path: '/alteracoes',
    getParentRoute: () => AdminLotesBatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analise': typeof AdminAnaliseRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/rota/$routeCode': typeof RotaRouteCodeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/rota/': typeof RotaIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRouteWithChildren
  '/admin/motoristas/$driverId': typeof AdminMotoristasDriverIdRoute
  '/rota/$routeCode/confirmada': typeof RotaRouteCodeConfirmadaRoute
  '/rota/$routeCode/resumo': typeof RotaRouteCodeResumoRoute
  '/admin/lotes/': typeof AdminLotesIndexRoute
  '/admin/motoristas/': typeof AdminMotoristasIndexRoute
  '/rota/$routeCode/': typeof RotaRouteCodeIndexRoute
  '/admin/lotes/$batchId/alteracoes': typeof AdminLotesBatchIdAlteracoesRoute
  '/rota/$routeCode/pracas/$squareId': typeof RotaRouteCodePracasSquareIdRoute
  '/rota/$routeCode/pracas/': typeof RotaRouteCodePracasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analise': typeof AdminAnaliseRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/admin': typeof AdminIndexRoute
  '/rota': typeof RotaIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRouteWithChildren
  '/admin/motoristas/$driverId': typeof AdminMotoristasDriverIdRoute
  '/rota/$routeCode/confirmada': typeof RotaRouteCodeConfirmadaRoute
  '/rota/$routeCode/resumo': typeof RotaRouteCodeResumoRoute
  '/admin/lotes': typeof AdminLotesIndexRoute
  '/admin/motoristas': typeof AdminMotoristasIndexRoute
  '/rota/$routeCode': typeof RotaRouteCodeIndexRoute
  '/admin/lotes/$batchId/alteracoes': typeof AdminLotesBatchIdAlteracoesRoute
  '/rota/$routeCode/pracas/$squareId': typeof RotaRouteCodePracasSquareIdRoute
  '/rota/$routeCode/pracas': typeof RotaRouteCodePracasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analise': typeof AdminAnaliseRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/rota/$routeCode': typeof RotaRouteCodeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/rota/': typeof RotaIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRouteWithChildren
  '/admin/motoristas/$driverId': typeof AdminMotoristasDriverIdRoute
  '/rota/$routeCode/confirmada': typeof RotaRouteCodeConfirmadaRoute
  '/rota/$routeCode/resumo': typeof RotaRouteCodeResumoRoute
  '/admin/lotes/': typeof AdminLotesIndexRoute
  '/admin/motoristas/': typeof AdminMotoristasIndexRoute
  '/rota/$routeCode/': typeof RotaRouteCodeIndexRoute
  '/admin/lotes/$batchId/alteracoes': typeof AdminLotesBatchIdAlteracoesRoute
  '/rota/$routeCode/pracas/$squareId': typeof RotaRouteCodePracasSquareIdRoute
  '/rota/$routeCode/pracas/': typeof RotaRouteCodePracasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analise'
    | '/admin/import'
    | '/admin/login'
    | '/admin/veiculos'
    | '/rota/$routeCode'
    | '/admin/'
    | '/rota/'
    | '/admin/lotes/$batchId'
    | '/admin/motoristas/$driverId'
    | '/rota/$routeCode/confirmada'
    | '/rota/$routeCode/resumo'
    | '/admin/lotes/'
    | '/admin/motoristas/'
    | '/rota/$routeCode/'
    | '/admin/lotes/$batchId/alteracoes'
    | '/rota/$routeCode/pracas/$squareId'
    | '/rota/$routeCode/pracas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analise'
    | '/admin/import'
    | '/admin/login'
    | '/admin/veiculos'
    | '/admin'
    | '/rota'
    | '/admin/lotes/$batchId'
    | '/admin/motoristas/$driverId'
    | '/rota/$routeCode/confirmada'
    | '/rota/$routeCode/resumo'
    | '/admin/lotes'
    | '/admin/motoristas'
    | '/rota/$routeCode'
    | '/admin/lotes/$batchId/alteracoes'
    | '/rota/$routeCode/pracas/$squareId'
    | '/rota/$routeCode/pracas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analise'
    | '/admin/import'
    | '/admin/login'
    | '/admin/veiculos'
    | '/rota/$routeCode'
    | '/admin/'
    | '/rota/'
    | '/admin/lotes/$batchId'
    | '/admin/motoristas/$driverId'
    | '/rota/$routeCode/confirmada'
    | '/rota/$routeCode/resumo'
    | '/admin/lotes/'
    | '/admin/motoristas/'
    | '/rota/$routeCode/'
    | '/admin/lotes/$batchId/alteracoes'
    | '/rota/$routeCode/pracas/$squareId'
    | '/rota/$routeCode/pracas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RotaRouteCodeRoute: typeof RotaRouteCodeRouteWithChildren
  RotaIndexRoute: typeof RotaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota/': {
      id: '/rota/'
      path: '/rota'
      fullPath: '/rota/'
      preLoaderRoute: typeof RotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rota/$routeCode': {
      id: '/rota/$routeCode'
      path: '/rota/$routeCode'
      fullPath: '/rota/$routeCode'
      preLoaderRoute: typeof RotaRouteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analise': {
      id: '/admin/analise'
      path: '/analise'
      fullPath: '/admin/analise'
      preLoaderRoute: typeof AdminAnaliseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rota/$routeCode/': {
      id: '/rota/$routeCode/'
      path: '/'
      fullPath: '/rota/$routeCode/'
      preLoaderRoute: typeof RotaRouteCodeIndexRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/admin/motoristas/': {
      id: '/admin/motoristas/'
      path: '/motoristas'
      fullPath: '/admin/motoristas/'
      preLoaderRoute: typeof AdminMotoristasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lotes/': {
      id: '/admin/lotes/'
      path: '/lotes'
      fullPath: '/admin/lotes/'
      preLoaderRoute: typeof AdminLotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rota/$routeCode/resumo': {
      id: '/rota/$routeCode/resumo'
      path: '/resumo'
      fullPath: '/rota/$routeCode/resumo'
      preLoaderRoute: typeof RotaRouteCodeResumoRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/rota/$routeCode/confirmada': {
      id: '/rota/$routeCode/confirmada'
      path: '/confirmada'
      fullPath: '/rota/$routeCode/confirmada'
      preLoaderRoute: typeof RotaRouteCodeConfirmadaRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/admin/motoristas/$driverId': {
      id: '/admin/motoristas/$driverId'
      path: '/motoristas/$driverId'
      fullPath: '/admin/motoristas/$driverId'
      preLoaderRoute: typeof AdminMotoristasDriverIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lotes/$batchId': {
      id: '/admin/lotes/$batchId'
      path: '/lotes/$batchId'
      fullPath: '/admin/lotes/$batchId'
      preLoaderRoute: typeof AdminLotesBatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rota/$routeCode/pracas/': {
      id: '/rota/$routeCode/pracas/'
      path: '/pracas'
      fullPath: '/rota/$routeCode/pracas/'
      preLoaderRoute: typeof RotaRouteCodePracasIndexRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/rota/$routeCode/pracas/$squareId': {
      id: '/rota/$routeCode/pracas/$squareId'
      path: '/pracas/$squareId'
      fullPath: '/rota/$routeCode/pracas/$squareId'
      preLoaderRoute: typeof RotaRouteCodePracasSquareIdRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/admin/lotes/$batchId/alteracoes': {
      id: '/admin/lotes/$batchId/alteracoes'
      path: '/alteracoes'
      fullPath: '/admin/lotes/$batchId/alteracoes'
      preLoaderRoute: typeof AdminLotesBatchIdAlteracoesRouteImport
      parentRoute: typeof AdminLotesBatchIdRoute
    }
  }
}

interface AdminLotesBatchIdRouteChildren {
  AdminLotesBatchIdAlteracoesRoute: typeof AdminLotesBatchIdAlteracoesRoute
}

const AdminLotesBatchIdRouteChildren: AdminLotesBatchIdRouteChildren = {
  AdminLotesBatchIdAlteracoesRoute: AdminLotesBatchIdAlteracoesRoute,
}

const AdminLotesBatchIdRouteWithChildren =
  AdminLotesBatchIdRoute._addFileChildren(AdminLotesBatchIdRouteChildren)

interface AdminRouteChildren {
  AdminAnaliseRoute: typeof AdminAnaliseRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLotesBatchIdRoute: typeof AdminLotesBatchIdRouteWithChildren
  AdminMotoristasDriverIdRoute: typeof AdminMotoristasDriverIdRoute
  AdminLotesIndexRoute: typeof AdminLotesIndexRoute
  AdminMotoristasIndexRoute: typeof AdminMotoristasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnaliseRoute: AdminAnaliseRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLotesBatchIdRoute: AdminLotesBatchIdRouteWithChildren,
  AdminMotoristasDriverIdRoute: AdminMotoristasDriverIdRoute,
  AdminLotesIndexRoute: AdminLotesIndexRoute,
  AdminMotoristasIndexRoute: AdminMotoristasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RotaRouteCodeRouteChildren {
  RotaRouteCodeConfirmadaRoute: typeof RotaRouteCodeConfirmadaRoute
  RotaRouteCodeResumoRoute: typeof RotaRouteCodeResumoRoute
  RotaRouteCodeIndexRoute: typeof RotaRouteCodeIndexRoute
  RotaRouteCodePracasSquareIdRoute: typeof RotaRouteCodePracasSquareIdRoute
  RotaRouteCodePracasIndexRoute: typeof RotaRouteCodePracasIndexRoute
}

const RotaRouteCodeRouteChildren: RotaRouteCodeRouteChildren = {
  RotaRouteCodeConfirmadaRoute: RotaRouteCodeConfirmadaRoute,
  RotaRouteCodeResumoRoute: RotaRouteCodeResumoRoute,
  RotaRouteCodeIndexRoute: RotaRouteCodeIndexRoute,
  RotaRouteCodePracasSquareIdRoute: RotaRouteCodePracasSquareIdRoute,
  RotaRouteCodePracasIndexRoute: RotaRouteCodePracasIndexRoute,
}

const RotaRouteCodeRouteWithChildren = RotaRouteCodeRoute._addFileChildren(
  RotaRouteCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RotaRouteCodeRoute: RotaRouteCodeRouteWithChildren,
  RotaIndexRoute: RotaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
