/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RotaIndexRouteImport } from './routes/rota.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RotaRouteCodeRouteImport } from './routes/rota.$routeCode'
import { Route as AdminMotoristasRouteImport } from './routes/admin.motoristas'
import { Route as AdminLotesRouteImport } from './routes/admin.lotes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as RotaRouteCodeIndexRouteImport } from './routes/rota.$routeCode.index'
import { Route as RotaRouteCodeResumoRouteImport } from './routes/rota.$routeCode.resumo'
import { Route as RotaRouteCodePracasRouteImport } from './routes/rota.$routeCode.pracas'
import { Route as RotaRouteCodeConfirmadaRouteImport } from './routes/rota.$routeCode.confirmada'
import { Route as AdminLotesBatchIdRouteImport } from './routes/admin.lotes.$batchId'
import { Route as RotaRouteCodePracasSquareIdRouteImport } from './routes/rota.$routeCode.pracas.$squareId'
import { Route as AdminLotesBatchIdAlteracoesRouteImport } from './routes/admin.lotes.$batchId.alteracoes'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaIndexRoute = RotaIndexRouteImport.update({
  id: '/rota/',
  path: '/rota/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RotaRouteCodeRoute = RotaRouteCodeRouteImport.update({
  id: '/rota/$routeCode',
  path: '/rota/$routeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotesRoute = AdminLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const RotaRouteCodeIndexRoute = RotaRouteCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RotaRouteCodeRoute,
} as any)
const RotaRouteCodeResumoRoute = RotaRouteCodeResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => RotaRouteCodeRoute,
} as any)
const RotaRouteCodePracasRoute = RotaRouteCodePracasRouteImport.update({
  id: '/pracas',
  path: '/pracas',
  getParentRoute: () => RotaRouteCodeRoute,
} as any)
const RotaRouteCodeConfirmadaRoute = RotaRouteCodeConfirmadaRouteImport.update({
  id: '/confirmada',
  path: '/confirmada',
  getParentRoute: () => RotaRouteCodeRoute,
} as any)
const AdminLotesBatchIdRoute = AdminLotesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => AdminLotesRoute,
} as any)
const RotaRouteCodePracasSquareIdRoute =
  RotaRouteCodePracasSquareIdRouteImport.update({
    id: '/$squareId',
    path: '/$squareId',
    getParentRoute: () => RotaRouteCodePracasRoute,
  } as any)
const AdminLotesBatchIdAlteracoesRoute =
  AdminLotesBatchIdAlteracoesRouteImport.update({
    id: '/alteracoes',
    path: '/alteracoes',
    getParentRoute: () => AdminLotesBatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lotes': typeof AdminLotesRouteWithChildren
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/rota/$routeCode': typeof RotaRouteCodeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/rota/': typeof RotaIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRouteWithChildren
  '/rota/$routeCode/confirmada': typeof RotaRouteCodeConfirmadaRoute
  '/rota/$routeCode/pracas': typeof RotaRouteCodePracasRouteWithChildren
  '/rota/$routeCode/resumo': typeof RotaRouteCodeResumoRoute
  '/rota/$routeCode/': typeof RotaRouteCodeIndexRoute
  '/admin/lotes/$batchId/alteracoes': typeof AdminLotesBatchIdAlteracoesRoute
  '/rota/$routeCode/pracas/$squareId': typeof RotaRouteCodePracasSquareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lotes': typeof AdminLotesRouteWithChildren
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin': typeof AdminIndexRoute
  '/rota': typeof RotaIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRouteWithChildren
  '/rota/$routeCode/confirmada': typeof RotaRouteCodeConfirmadaRoute
  '/rota/$routeCode/pracas': typeof RotaRouteCodePracasRouteWithChildren
  '/rota/$routeCode/resumo': typeof RotaRouteCodeResumoRoute
  '/rota/$routeCode': typeof RotaRouteCodeIndexRoute
  '/admin/lotes/$batchId/alteracoes': typeof AdminLotesBatchIdAlteracoesRoute
  '/rota/$routeCode/pracas/$squareId': typeof RotaRouteCodePracasSquareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/lotes': typeof AdminLotesRouteWithChildren
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/rota/$routeCode': typeof RotaRouteCodeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/rota/': typeof RotaIndexRoute
  '/admin/lotes/$batchId': typeof AdminLotesBatchIdRouteWithChildren
  '/rota/$routeCode/confirmada': typeof RotaRouteCodeConfirmadaRoute
  '/rota/$routeCode/pracas': typeof RotaRouteCodePracasRouteWithChildren
  '/rota/$routeCode/resumo': typeof RotaRouteCodeResumoRoute
  '/rota/$routeCode/': typeof RotaRouteCodeIndexRoute
  '/admin/lotes/$batchId/alteracoes': typeof AdminLotesBatchIdAlteracoesRoute
  '/rota/$routeCode/pracas/$squareId': typeof RotaRouteCodePracasSquareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/import'
    | '/admin/login'
    | '/admin/lotes'
    | '/admin/motoristas'
    | '/rota/$routeCode'
    | '/admin/'
    | '/rota/'
    | '/admin/lotes/$batchId'
    | '/rota/$routeCode/confirmada'
    | '/rota/$routeCode/pracas'
    | '/rota/$routeCode/resumo'
    | '/rota/$routeCode/'
    | '/admin/lotes/$batchId/alteracoes'
    | '/rota/$routeCode/pracas/$squareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/import'
    | '/admin/login'
    | '/admin/lotes'
    | '/admin/motoristas'
    | '/admin'
    | '/rota'
    | '/admin/lotes/$batchId'
    | '/rota/$routeCode/confirmada'
    | '/rota/$routeCode/pracas'
    | '/rota/$routeCode/resumo'
    | '/rota/$routeCode'
    | '/admin/lotes/$batchId/alteracoes'
    | '/rota/$routeCode/pracas/$squareId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/import'
    | '/admin/login'
    | '/admin/lotes'
    | '/admin/motoristas'
    | '/rota/$routeCode'
    | '/admin/'
    | '/rota/'
    | '/admin/lotes/$batchId'
    | '/rota/$routeCode/confirmada'
    | '/rota/$routeCode/pracas'
    | '/rota/$routeCode/resumo'
    | '/rota/$routeCode/'
    | '/admin/lotes/$batchId/alteracoes'
    | '/rota/$routeCode/pracas/$squareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RotaRouteCodeRoute: typeof RotaRouteCodeRouteWithChildren
  RotaIndexRoute: typeof RotaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota/': {
      id: '/rota/'
      path: '/rota'
      fullPath: '/rota/'
      preLoaderRoute: typeof RotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rota/$routeCode': {
      id: '/rota/$routeCode'
      path: '/rota/$routeCode'
      fullPath: '/rota/$routeCode'
      preLoaderRoute: typeof RotaRouteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lotes': {
      id: '/admin/lotes'
      path: '/lotes'
      fullPath: '/admin/lotes'
      preLoaderRoute: typeof AdminLotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rota/$routeCode/': {
      id: '/rota/$routeCode/'
      path: '/'
      fullPath: '/rota/$routeCode/'
      preLoaderRoute: typeof RotaRouteCodeIndexRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/rota/$routeCode/resumo': {
      id: '/rota/$routeCode/resumo'
      path: '/resumo'
      fullPath: '/rota/$routeCode/resumo'
      preLoaderRoute: typeof RotaRouteCodeResumoRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/rota/$routeCode/pracas': {
      id: '/rota/$routeCode/pracas'
      path: '/pracas'
      fullPath: '/rota/$routeCode/pracas'
      preLoaderRoute: typeof RotaRouteCodePracasRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/rota/$routeCode/confirmada': {
      id: '/rota/$routeCode/confirmada'
      path: '/confirmada'
      fullPath: '/rota/$routeCode/confirmada'
      preLoaderRoute: typeof RotaRouteCodeConfirmadaRouteImport
      parentRoute: typeof RotaRouteCodeRoute
    }
    '/admin/lotes/$batchId': {
      id: '/admin/lotes/$batchId'
      path: '/$batchId'
      fullPath: '/admin/lotes/$batchId'
      preLoaderRoute: typeof AdminLotesBatchIdRouteImport
      parentRoute: typeof AdminLotesRoute
    }
    '/rota/$routeCode/pracas/$squareId': {
      id: '/rota/$routeCode/pracas/$squareId'
      path: '/$squareId'
      fullPath: '/rota/$routeCode/pracas/$squareId'
      preLoaderRoute: typeof RotaRouteCodePracasSquareIdRouteImport
      parentRoute: typeof RotaRouteCodePracasRoute
    }
    '/admin/lotes/$batchId/alteracoes': {
      id: '/admin/lotes/$batchId/alteracoes'
      path: '/alteracoes'
      fullPath: '/admin/lotes/$batchId/alteracoes'
      preLoaderRoute: typeof AdminLotesBatchIdAlteracoesRouteImport
      parentRoute: typeof AdminLotesBatchIdRoute
    }
  }
}

interface AdminLotesBatchIdRouteChildren {
  AdminLotesBatchIdAlteracoesRoute: typeof AdminLotesBatchIdAlteracoesRoute
}

const AdminLotesBatchIdRouteChildren: AdminLotesBatchIdRouteChildren = {
  AdminLotesBatchIdAlteracoesRoute: AdminLotesBatchIdAlteracoesRoute,
}

const AdminLotesBatchIdRouteWithChildren =
  AdminLotesBatchIdRoute._addFileChildren(AdminLotesBatchIdRouteChildren)

interface AdminLotesRouteChildren {
  AdminLotesBatchIdRoute: typeof AdminLotesBatchIdRouteWithChildren
}

const AdminLotesRouteChildren: AdminLotesRouteChildren = {
  AdminLotesBatchIdRoute: AdminLotesBatchIdRouteWithChildren,
}

const AdminLotesRouteWithChildren = AdminLotesRoute._addFileChildren(
  AdminLotesRouteChildren,
)

interface AdminRouteChildren {
  AdminImportRoute: typeof AdminImportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLotesRoute: typeof AdminLotesRouteWithChildren
  AdminMotoristasRoute: typeof AdminMotoristasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportRoute: AdminImportRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLotesRoute: AdminLotesRouteWithChildren,
  AdminMotoristasRoute: AdminMotoristasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RotaRouteCodePracasRouteChildren {
  RotaRouteCodePracasSquareIdRoute: typeof RotaRouteCodePracasSquareIdRoute
}

const RotaRouteCodePracasRouteChildren: RotaRouteCodePracasRouteChildren = {
  RotaRouteCodePracasSquareIdRoute: RotaRouteCodePracasSquareIdRoute,
}

const RotaRouteCodePracasRouteWithChildren =
  RotaRouteCodePracasRoute._addFileChildren(RotaRouteCodePracasRouteChildren)

interface RotaRouteCodeRouteChildren {
  RotaRouteCodeConfirmadaRoute: typeof RotaRouteCodeConfirmadaRoute
  RotaRouteCodePracasRoute: typeof RotaRouteCodePracasRouteWithChildren
  RotaRouteCodeResumoRoute: typeof RotaRouteCodeResumoRoute
  RotaRouteCodeIndexRoute: typeof RotaRouteCodeIndexRoute
}

const RotaRouteCodeRouteChildren: RotaRouteCodeRouteChildren = {
  RotaRouteCodeConfirmadaRoute: RotaRouteCodeConfirmadaRoute,
  RotaRouteCodePracasRoute: RotaRouteCodePracasRouteWithChildren,
  RotaRouteCodeResumoRoute: RotaRouteCodeResumoRoute,
  RotaRouteCodeIndexRoute: RotaRouteCodeIndexRoute,
}

const RotaRouteCodeRouteWithChildren = RotaRouteCodeRoute._addFileChildren(
  RotaRouteCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RotaRouteCodeRoute: RotaRouteCodeRouteWithChildren,
  RotaIndexRoute: RotaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
